{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "sys:edge",
        "objLabel" : ""
      },
      "predicates" : [ {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "name" : "incorrectFeature",
              "scope" : "local",
              "dataType" : ""
            }
          }, {
            "kind" : "StaticValue",
            "attributes" : {
              "datatype" : "string",
              "value" : "FUTURE_AADT"
            }
          } ]
        }, {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "name" : "correctParameters",
              "scope" : "local",
              "dataType" : ""
            }
          }, {
            "kind" : "StaticValue",
            "attributes" : {
              "datatype" : "string",
              "value" : "greater than all AADT objects' Value_Numeric and less than all AADT objects' Value_Numeric times 3"
            }
          } ]
        }, {
          "kind" : "ForPredicateOperation",
          "attributes" : {
            "classLabel" : "FUTURE_AADT",
            "objLabel" : "",
            "n" : "0"
          },
          "predicates" : [ {
            "kind" : "ReferentialPredicate",
            "attributes" : {
              "classRef1" : "FUTURE_AADT",
              "refName" : "sys:line_to_edge",
              "classRef2" : "sys:edge",
              "objRef2" : "",
              "objRef1" : ""
            }
          }, {
            "kind" : "SequenceOperation",
            "attributes" : {
              "template_num_params" : "2",
              "template_name" : "Invalid Value Numeric(sys.edge)",
              "template_id" : "ACTION://HPMS/Templates/Invalid Value Numeric(sys.edge)",
              "template_type" : "Action"
            },
            "predicates" : [ {
              "kind" : "ReportOperation",
              "attributes" : {
                "scope" : "per-object",
                "label" : "Invalid Value Numeric"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "sys:edge",
                  "template_param" : "2"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Numeric",
                  "classRef" : "FUTURE_AADT",
                  "template_param" : "1"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "sys:edge",
                      "template_param" : "2"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Numeric",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Numeric",
                      "classRef" : "FUTURE_AADT",
                      "template_param" : "1"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "name" : "incorrectFeature",
                        "scope" : "local",
                        "dataType" : ""
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " has invalid Value_Numeric (is not "
                      }
                    }, {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "name" : "correctParameters",
                        "scope" : "local",
                        "dataType" : ""
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : ")."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}