{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "sys:edge",
        "objLabel" : ""
      },
      "predicates" : [ {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "ForPredicateOperation",
          "attributes" : {
            "classLabel" : "IRI",
            "objLabel" : "",
            "n" : "0"
          },
          "predicates" : [ {
            "kind" : "AndPredicate",
            "predicates" : [ {
              "kind" : "ReferentialPredicate",
              "attributes" : {
                "classRef1" : "IRI",
                "refName" : "sys:line_to_edge",
                "classRef2" : "sys:edge",
                "objRef2" : "",
                "objRef1" : ""
              }
            }, {
              "kind" : "NotPredicate",
              "predicates" : [ {
                "kind" : "RelationalPredicate",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "Value_Date",
                    "classRef" : "IRI"
                  }
                }, {
                  "kind" : "GreaterEqualsRelation"
                }, {
                  "kind" : "DifferenceValue",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "IRI"
                    }
                  }, {
                    "kind" : "StaticValue",
                    "attributes" : {
                      "datatype" : "integer",
                      "value" : "2"
                    }
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "scope" : "local",
                  "dataType" : "",
                  "name" : "incorrectFeature"
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "IRI"
                }
              } ]
            }, {
              "kind" : "ReportOperation",
              "attributes" : {
                "scope" : "per-object",
                "label" : "Invalid Value Numeric"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "IRI"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Date",
                  "classRef" : "IRI"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Year_Record",
                  "classRef" : "IRI"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "IRI"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "IRI"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "IRI"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "incorrectFeature"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object's Value_Date is not greater than or equal to its Year_Record minus 2."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        }, {
          "kind" : "ForPredicateOperation",
          "attributes" : {
            "classLabel" : "RUTTING",
            "objLabel" : "",
            "n" : "0"
          },
          "predicates" : [ {
            "kind" : "AndPredicate",
            "predicates" : [ {
              "kind" : "ReferentialPredicate",
              "attributes" : {
                "classRef1" : "RUTTING",
                "refName" : "sys:line_to_edge",
                "classRef2" : "sys:edge",
                "objRef2" : "",
                "objRef1" : ""
              }
            }, {
              "kind" : "NotPredicate",
              "predicates" : [ {
                "kind" : "RelationalPredicate",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "Value_Date",
                    "classRef" : "RUTTING"
                  }
                }, {
                  "kind" : "GreaterEqualsRelation"
                }, {
                  "kind" : "DifferenceValue",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "RUTTING"
                    }
                  }, {
                    "kind" : "StaticValue",
                    "attributes" : {
                      "datatype" : "integer",
                      "value" : "2"
                    }
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "scope" : "local",
                  "dataType" : "",
                  "name" : "incorrectFeature"
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "RUTTING"
                }
              } ]
            }, {
              "kind" : "ReportOperation",
              "attributes" : {
                "scope" : "per-object",
                "label" : "Invalid Value Numeric"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "RUTTING"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Date",
                  "classRef" : "RUTTING"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Year_Record",
                  "classRef" : "RUTTING"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "RUTTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "RUTTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "RUTTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "incorrectFeature"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object's Value_Date is not greater than or equal to its Year_Record minus 2."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        }, {
          "kind" : "ForPredicateOperation",
          "attributes" : {
            "classLabel" : "FAULTING",
            "objLabel" : "",
            "n" : "0"
          },
          "predicates" : [ {
            "kind" : "AndPredicate",
            "predicates" : [ {
              "kind" : "ReferentialPredicate",
              "attributes" : {
                "classRef1" : "FAULTING",
                "refName" : "sys:line_to_edge",
                "classRef2" : "sys:edge",
                "objRef2" : "",
                "objRef1" : ""
              }
            }, {
              "kind" : "NotPredicate",
              "predicates" : [ {
                "kind" : "RelationalPredicate",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "Value_Date",
                    "classRef" : "FAULTING"
                  }
                }, {
                  "kind" : "GreaterEqualsRelation"
                }, {
                  "kind" : "DifferenceValue",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "FAULTING"
                    }
                  }, {
                    "kind" : "StaticValue",
                    "attributes" : {
                      "datatype" : "integer",
                      "value" : "2"
                    }
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "scope" : "local",
                  "dataType" : "",
                  "name" : "incorrectFeature"
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "FAULTING"
                }
              } ]
            }, {
              "kind" : "ReportOperation",
              "attributes" : {
                "scope" : "per-object",
                "label" : "Invalid Value Numeric"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "FAULTING"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Date",
                  "classRef" : "FAULTING"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Year_Record",
                  "classRef" : "FAULTING"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "FAULTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "FAULTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "FAULTING"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "incorrectFeature"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object's Value_Date is not greater than or equal to its Year_Record minus 2."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        }, {
          "kind" : "ForPredicateOperation",
          "attributes" : {
            "classLabel" : "CRACKING_PERCENT",
            "objLabel" : "",
            "n" : "0"
          },
          "predicates" : [ {
            "kind" : "AndPredicate",
            "predicates" : [ {
              "kind" : "ReferentialPredicate",
              "attributes" : {
                "classRef1" : "CRACKING_PERCENT",
                "refName" : "sys:line_to_edge",
                "classRef2" : "sys:edge",
                "objRef2" : "",
                "objRef1" : ""
              }
            }, {
              "kind" : "NotPredicate",
              "predicates" : [ {
                "kind" : "RelationalPredicate",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "Value_Date",
                    "classRef" : "CRACKING_PERCENT"
                  }
                }, {
                  "kind" : "GreaterEqualsRelation"
                }, {
                  "kind" : "DifferenceValue",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "CRACKING_PERCENT"
                    }
                  }, {
                    "kind" : "StaticValue",
                    "attributes" : {
                      "datatype" : "integer",
                      "value" : "2"
                    }
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "scope" : "local",
                  "dataType" : "",
                  "name" : "incorrectFeature"
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "CRACKING_PERCENT"
                }
              } ]
            }, {
              "kind" : "ReportOperation",
              "attributes" : {
                "scope" : "per-object",
                "label" : "Invalid Value Numeric"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "CRACKING_PERCENT"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Date",
                  "classRef" : "CRACKING_PERCENT"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Year_Record",
                  "classRef" : "CRACKING_PERCENT"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "CRACKING_PERCENT"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Value_Date",
                      "classRef" : "CRACKING_PERCENT"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Year_Record",
                      "classRef" : "CRACKING_PERCENT"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "incorrectFeature"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object's Value_Date is not greater than or equal to its Year_Record minus 2."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}