{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "FACILITY_TYPE",
        "objLabel" : ""
      },
      "predicates" : [ {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "scope" : "local",
              "dataType" : "",
              "name" : "Feature_Class"
            }
          }, {
            "kind" : "ClassValue",
            "attributes" : {
              "objRef" : "",
              "classRef" : "FACILITY_TYPE"
            }
          } ]
        }, {
          "kind" : "ConditionalOperation",
          "predicates" : [ {
            "kind" : "RelationalPredicate",
            "predicates" : [ {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "",
                "propName" : "Value_Numeric",
                "classRef" : "FACILITY_TYPE"
              }
            }, {
              "kind" : "NotEqualsRelation"
            }, {
              "kind" : "BuiltinFnValue",
              "attributes" : {
                "fnName" : "floor"
              },
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Numeric",
                  "classRef" : "FACILITY_TYPE"
                }
              } ]
            } ]
          }, {
            "kind" : "CreateObjectOperation",
            "attributes" : {
              "classLabel" : "Report",
              "objLabel" : ""
            },
            "predicates" : [ {
              "kind" : "SequenceOperation",
              "predicates" : [ {
                "kind" : "AssignmentOperation",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "geometry",
                    "classRef" : "Report"
                  }
                }, {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "geometry",
                    "classRef" : "FACILITY_TYPE"
                  }
                } ]
              }, {
                "kind" : "AssignmentOperation",
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "Note",
                    "classRef" : "Report"
                  }
                }, {
                  "kind" : "SummedValue",
                  "predicates" : [ {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "Feature_Class"
                    }
                  }, {
                    "kind" : "StaticValue",
                    "attributes" : {
                      "datatype" : "string",
                      "value" : " object's Value_Numeric is not a whole number."
                    }
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "ConditionalOperation",
            "predicates" : [ {
              "kind" : "RelationalPredicate",
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Numeric",
                  "classRef" : "FACILITY_TYPE"
                }
              }, {
                "kind" : "EqualsRelation"
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "integer",
                  "value" : "3"
                }
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "FACILITY_TYPE"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "Feature_Class"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object is equals 3."
                      }
                    } ]
                  } ]
                } ]
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "Report",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "FACILITY_TYPE"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "Note",
                      "classRef" : "Report"
                    }
                  }, {
                    "kind" : "SummedValue",
                    "predicates" : [ {
                      "kind" : "TemporaryValue",
                      "attributes" : {
                        "scope" : "local",
                        "dataType" : "",
                        "name" : "Feature_Class"
                      }
                    }, {
                      "kind" : "StaticValue",
                      "attributes" : {
                        "datatype" : "string",
                        "value" : " object is not in correct range."
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}