{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "FACILITY_TYPE missing F_SYSTEM in (1,2,3,4,5,6,7)",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "sys:edge",
        "objLabel" : ""
      },
      "predicates" : [ {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "ConditionalOperation",
          "predicates" : [ {
            "kind" : "ExistsPredicate",
            "attributes" : {
              "classLabel" : "FACILITY_TYPE",
              "n" : "1",
              "objLabel" : "A",
              "qualifier" : "at least"
            },
            "predicates" : [ {
              "kind" : "AndPredicate",
              "predicates" : [ {
                "kind" : "ReferentialPredicate",
                "attributes" : {
                  "classRef1" : "FACILITY_TYPE",
                  "refName" : "sys:line_to_edge",
                  "classRef2" : "sys:edge",
                  "objRef2" : "",
                  "objRef1" : "A"
                }
              }, {
                "kind" : "ExistsPredicate",
                "attributes" : {
                  "classLabel" : "FACILITY_TYPE",
                  "n" : "1",
                  "objLabel" : "B",
                  "qualifier" : "at least"
                },
                "predicates" : [ {
                  "kind" : "AndPredicate",
                  "predicates" : [ {
                    "kind" : "ReferentialPredicate",
                    "attributes" : {
                      "classRef1" : "FACILITY_TYPE",
                      "refName" : "sys:line_to_edge",
                      "classRef2" : "sys:edge",
                      "objRef2" : "",
                      "objRef1" : "B"
                    }
                  }, {
                    "kind" : "RelationalPredicate",
                    "predicates" : [ {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "A",
                        "propName" : "Route_ID",
                        "classRef" : "FACILITY_TYPE"
                      }
                    }, {
                      "kind" : "EqualsRelation"
                    }, {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "B",
                        "propName" : "Route_ID",
                        "classRef" : "FACILITY_TYPE"
                      }
                    } ]
                  } ]
                } ]
              } ]
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "name" : "invalidFeature",
                  "scope" : "local",
                  "dataType" : ""
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "FACILITY_TYPE"
                }
              } ]
            }, {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "name" : "reasonInvalid",
                  "scope" : "local",
                  "dataType" : ""
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "duplicate FACILITY_TYPE"
                }
              } ]
            }, {
              "kind" : "SequenceOperation",
              "attributes" : {
                "template_num_params" : "1",
                "template_name" : "Invalid Feature",
                "template_id" : "ACTION://HPMS/Templates/Invalid Feature",
                "template_type" : "Action"
              },
              "predicates" : [ {
                "kind" : "ReportOperation",
                "attributes" : {
                  "scope" : "per-object",
                  "label" : "Missing Object"
                },
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "geometry",
                    "classRef" : "sys:edge",
                    "template_param" : "1"
                  }
                } ]
              }, {
                "kind" : "CreateObjectOperation",
                "attributes" : {
                  "classLabel" : "Report",
                  "objLabel" : ""
                },
                "predicates" : [ {
                  "kind" : "SequenceOperation",
                  "predicates" : [ {
                    "kind" : "AssignmentOperation",
                    "predicates" : [ {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "geometry",
                        "classRef" : "Report"
                      }
                    }, {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "geometry",
                        "classRef" : "sys:edge",
                        "template_param" : "1"
                      }
                    } ]
                  }, {
                    "kind" : "AssignmentOperation",
                    "predicates" : [ {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "Note",
                        "classRef" : "Report"
                      }
                    }, {
                      "kind" : "SummedValue",
                      "predicates" : [ {
                        "kind" : "StaticValue",
                        "attributes" : {
                          "datatype" : "string",
                          "value" : "Invalid"
                        }
                      }, {
                        "kind" : "TemporaryValue",
                        "attributes" : {
                          "name" : "invalidFeature",
                          "scope" : "local",
                          "dataType" : ""
                        }
                      }, {
                        "kind" : "StaticValue",
                        "attributes" : {
                          "datatype" : "string",
                          "value" : " Object ("
                        }
                      }, {
                        "kind" : "TemporaryValue",
                        "attributes" : {
                          "name" : "reasonInvalid",
                          "scope" : "local",
                          "dataType" : ""
                        }
                      }, {
                        "kind" : "StaticValue",
                        "attributes" : {
                          "datatype" : "string",
                          "value" : ")"
                        }
                      } ]
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        }, {
          "kind" : "ConditionalOperation",
          "predicates" : [ {
            "kind" : "ExistsPredicate",
            "attributes" : {
              "classLabel" : "FACILITY_TYPE",
              "n" : "0",
              "objLabel" : "",
              "qualifier" : "exactly"
            },
            "predicates" : [ {
              "kind" : "ReferentialPredicate",
              "attributes" : {
                "classRef1" : "FACILITY_TYPE",
                "refName" : "sys:line_to_edge",
                "classRef2" : "sys:edge",
                "objRef2" : "",
                "objRef1" : ""
              }
            } ]
          }, {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "TemporaryValue",
                "attributes" : {
                  "name" : "missingFeature",
                  "scope" : "local",
                  "dataType" : ""
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : "FACILITY_TYPE"
                }
              } ]
            }, {
              "kind" : "SequenceOperation",
              "attributes" : {
                "template_num_params" : "1",
                "template_name" : "Missing Feature",
                "template_id" : "ACTION://HPMS/Templates/Missing Feature",
                "template_type" : "Action"
              },
              "predicates" : [ {
                "kind" : "ReportOperation",
                "attributes" : {
                  "scope" : "per-object",
                  "label" : "Missing Object"
                },
                "predicates" : [ {
                  "kind" : "DynamicValue",
                  "attributes" : {
                    "objRef" : "",
                    "propName" : "geometry",
                    "classRef" : "sys:edge",
                    "template_param" : "1"
                  }
                } ]
              }, {
                "kind" : "CreateObjectOperation",
                "attributes" : {
                  "classLabel" : "Report",
                  "objLabel" : ""
                },
                "predicates" : [ {
                  "kind" : "SequenceOperation",
                  "predicates" : [ {
                    "kind" : "AssignmentOperation",
                    "predicates" : [ {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "geometry",
                        "classRef" : "Report"
                      }
                    }, {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "geometry",
                        "classRef" : "sys:edge",
                        "template_param" : "1"
                      }
                    } ]
                  }, {
                    "kind" : "AssignmentOperation",
                    "predicates" : [ {
                      "kind" : "DynamicValue",
                      "attributes" : {
                        "objRef" : "",
                        "propName" : "Note",
                        "classRef" : "Report"
                      }
                    }, {
                      "kind" : "SummedValue",
                      "predicates" : [ {
                        "kind" : "StaticValue",
                        "attributes" : {
                          "datatype" : "string",
                          "value" : "Missing "
                        }
                      }, {
                        "kind" : "TemporaryValue",
                        "attributes" : {
                          "name" : "missingFeature",
                          "scope" : "local",
                          "dataType" : ""
                        }
                      }, {
                        "kind" : "StaticValue",
                        "attributes" : {
                          "datatype" : "string",
                          "value" : " Object"
                        }
                      } ]
                    } ]
                  }, {
                    "kind" : "ForPredicateOperation",
                    "attributes" : {
                      "classLabel" : "ARNOLD",
                      "objLabel" : "",
                      "n" : "0"
                    },
                    "predicates" : [ {
                      "kind" : "ReferentialPredicate",
                      "attributes" : {
                        "classRef1" : "ARNOLD",
                        "refName" : "sys:line_to_edge",
                        "template_param_2" : "1",
                        "classRef2" : "sys:edge",
                        "objRef2" : "",
                        "objRef1" : ""
                      }
                    }, {
                      "kind" : "SequenceOperation",
                      "predicates" : [ {
                        "kind" : "AssignmentOperation",
                        "predicates" : [ {
                          "kind" : "DynamicValue",
                          "attributes" : {
                            "objRef" : "",
                            "propName" : "BeginMile",
                            "classRef" : "Report"
                          }
                        }, {
                          "kind" : "BuiltinFnValue",
                          "attributes" : {
                            "fnName" : "measure_from_point"
                          },
                          "predicates" : [ {
                            "kind" : "DynamicValue",
                            "attributes" : {
                              "objRef" : "",
                              "propName" : "geometry",
                              "classRef" : "ARNOLD"
                            }
                          }, {
                            "kind" : "BuiltinFnValue",
                            "attributes" : {
                              "fnName" : "start_of"
                            },
                            "predicates" : [ {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "geometry",
                                "classRef" : "sys:edge",
                                "template_param" : "1"
                              }
                            } ]
                          } ]
                        } ]
                      }, {
                        "kind" : "AssignmentOperation",
                        "predicates" : [ {
                          "kind" : "DynamicValue",
                          "attributes" : {
                            "objRef" : "",
                            "propName" : "EndMile",
                            "classRef" : "Report"
                          }
                        }, {
                          "kind" : "BuiltinFnValue",
                          "attributes" : {
                            "fnName" : "measure_from_point"
                          },
                          "predicates" : [ {
                            "kind" : "DynamicValue",
                            "attributes" : {
                              "objRef" : "",
                              "propName" : "geometry",
                              "classRef" : "ARNOLD"
                            }
                          }, {
                            "kind" : "BuiltinFnValue",
                            "attributes" : {
                              "fnName" : "end_of"
                            },
                            "predicates" : [ {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "geometry",
                                "classRef" : "sys:edge",
                                "template_param" : "1"
                              }
                            } ]
                          } ]
                        } ]
                      }, {
                        "kind" : "ConditionalOperation",
                        "predicates" : [ {
                          "kind" : "RelationalPredicate",
                          "predicates" : [ {
                            "kind" : "DynamicValue",
                            "attributes" : {
                              "objRef" : "",
                              "propName" : "BeginMile",
                              "classRef" : "Report"
                            }
                          }, {
                            "kind" : "GreaterRelation"
                          }, {
                            "kind" : "DynamicValue",
                            "attributes" : {
                              "objRef" : "",
                              "propName" : "EndMile",
                              "classRef" : "Report"
                            }
                          } ]
                        }, {
                          "kind" : "SequenceOperation",
                          "predicates" : [ {
                            "kind" : "AssignmentOperation",
                            "predicates" : [ {
                              "kind" : "TemporaryValue",
                              "attributes" : {
                                "name" : "FlipEM",
                                "scope" : "local",
                                "dataType" : ""
                              }
                            }, {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "BeginMile",
                                "classRef" : "Report"
                              }
                            } ]
                          }, {
                            "kind" : "AssignmentOperation",
                            "predicates" : [ {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "BeginMile",
                                "classRef" : "Report"
                              }
                            }, {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "EndMile",
                                "classRef" : "Report"
                              }
                            } ]
                          }, {
                            "kind" : "AssignmentOperation",
                            "predicates" : [ {
                              "kind" : "DynamicValue",
                              "attributes" : {
                                "objRef" : "",
                                "propName" : "EndMile",
                                "classRef" : "Report"
                              }
                            }, {
                              "kind" : "TemporaryValue",
                              "attributes" : {
                                "name" : "FlipEM",
                                "scope" : "local",
                                "dataType" : ""
                              }
                            } ]
                          } ]
                        } ]
                      } ]
                    } ]
                  } ]
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}