{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "Marks up the area of overlap only for overlapping features (MARKUP_LINE for line features, MARKUP_AREA for polygons). Avoids duplicate markups.",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "ARNOLD",
        "objLabel" : "all"
      },
      "predicates" : [ {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "scope" : "local",
              "dataType" : "",
              "name" : "rule name"
            }
          }, {
            "kind" : "BuiltinFnValue",
            "attributes" : {
              "fnName" : "rule_name"
            }
          } ]
        }, {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "scope" : "local",
              "dataType" : "",
              "name" : "class name"
            }
          }, {
            "kind" : "ClassValue",
            "attributes" : {
              "objRef" : "all",
              "classRef" : "ARNOLD"
            }
          } ]
        }, {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "scope" : "local",
              "dataType" : "",
              "name" : "feat_guid"
            }
          }, {
            "kind" : "BuiltinFnValue",
            "attributes" : {
              "fnName" : "to_string"
            },
            "predicates" : [ {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "all",
                "propName" : "Route_ID",
                "classRef" : "ARNOLD"
              }
            } ]
          } ]
        }, {
          "kind" : "AssignmentOperation",
          "predicates" : [ {
            "kind" : "TemporaryValue",
            "attributes" : {
              "scope" : "local",
              "dataType" : "",
              "name" : "comment"
            }
          }, {
            "kind" : "StaticValue",
            "attributes" : {
              "datatype" : "string",
              "value" : "Location of overlap"
            }
          } ]
        }, {
          "kind" : "ForAllElementsOperation",
          "attributes" : {
            "classLabel" : "",
            "objLabel" : "overlap"
          },
          "predicates" : [ {
            "kind" : "BuiltinFnValue",
            "attributes" : {
              "fnName" : "rule_hotspot_geometry"
            },
            "predicates" : [ {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "all",
                "propName" : "geometry",
                "classRef" : "ARNOLD"
              }
            } ]
          }, {
            "kind" : "ConditionalOperation",
            "predicates" : [ {
              "kind" : "ExistsPredicate",
              "attributes" : {
                "classLabel" : "MARKUP_LINE",
                "qualifier" : "exactly",
                "n" : "0",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "AndPredicate",
                "predicates" : [ {
                  "kind" : "RelationalPredicate",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "SpatialEqualsRelation"
                  }, {
                    "kind" : "ObjectValue",
                    "attributes" : {
                      "objRef" : "overlap",
                      "classRef" : ""
                    }
                  } ]
                }, {
                  "kind" : "RelationalPredicate",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "class",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "EqualsRelation"
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "class name"
                    }
                  } ]
                }, {
                  "kind" : "RelationalPredicate",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "violation",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "EqualsRelation"
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "rule name"
                    }
                  } ]
                } ]
              } ]
            }, {
              "kind" : "CreateObjectOperation",
              "attributes" : {
                "classLabel" : "MARKUP_LINE",
                "objLabel" : ""
              },
              "predicates" : [ {
                "kind" : "SequenceOperation",
                "predicates" : [ {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "class",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "class name"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "violation",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "rule name"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "geometry",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "ObjectValue",
                    "attributes" : {
                      "objRef" : "overlap",
                      "classRef" : ""
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "comment",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "comment"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "feat_guid",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "TemporaryValue",
                    "attributes" : {
                      "scope" : "local",
                      "dataType" : "",
                      "name" : "feat_guid"
                    }
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "rel_class",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "NullValue"
                  } ]
                }, {
                  "kind" : "AssignmentOperation",
                  "predicates" : [ {
                    "kind" : "DynamicValue",
                    "attributes" : {
                      "objRef" : "",
                      "propName" : "rel_f_guid",
                      "classRef" : "MARKUP_LINE"
                    }
                  }, {
                    "kind" : "NullValue"
                  } ]
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}