{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "Template",
      "predicates" : [ {
        "kind" : "Parameter",
        "attributes" : {
          "classLabel" : "AADT",
          "objLabel" : ""
        }
      }, {
        "kind" : "Parameter",
        "attributes" : {
          "classLabel" : "sys:edge",
          "objLabel" : ""
        }
      }, {
        "kind" : "SequenceOperation",
        "predicates" : [ {
          "kind" : "ReportOperation",
          "attributes" : {
            "scope" : "per-object",
            "label" : "Invalid Value Numeric"
          },
          "predicates" : [ {
            "kind" : "DynamicValue",
            "attributes" : {
              "objRef" : "",
              "propName" : "geometry",
              "classRef" : "sys:edge"
            }
          }, {
            "kind" : "DynamicValue",
            "attributes" : {
              "objRef" : "",
              "propName" : "Value_Numeric",
              "classRef" : "AADT"
            }
          } ]
        }, {
          "kind" : "CreateObjectOperation",
          "attributes" : {
            "classLabel" : "Report",
            "objLabel" : ""
          },
          "predicates" : [ {
            "kind" : "SequenceOperation",
            "predicates" : [ {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "Report"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "geometry",
                  "classRef" : "sys:edge"
                }
              } ]
            }, {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Numeric",
                  "classRef" : "Report"
                }
              }, {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Value_Numeric",
                  "classRef" : "AADT"
                }
              } ]
            }, {
              "kind" : "AssignmentOperation",
              "predicates" : [ {
                "kind" : "DynamicValue",
                "attributes" : {
                  "objRef" : "",
                  "propName" : "Note",
                  "classRef" : "Report"
                }
              }, {
                "kind" : "SummedValue",
                "predicates" : [ {
                  "kind" : "TemporaryValue",
                  "attributes" : {
                    "scope" : "local",
                    "dataType" : "",
                    "name" : "incorrectFeature"
                  }
                }, {
                  "kind" : "StaticValue",
                  "attributes" : {
                    "datatype" : "string",
                    "value" : " has invalid Value_Numeric (is not "
                  }
                }, {
                  "kind" : "TemporaryValue",
                  "attributes" : {
                    "scope" : "local",
                    "dataType" : "",
                    "name" : "correctParameters"
                  }
                }, {
                  "kind" : "StaticValue",
                  "attributes" : {
                    "datatype" : "string",
                    "value" : ")."
                  }
                } ]
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : true
}