{
  "comments" : "Branch: master\nRecent Commits:\n",
  "description" : "",
  "rootTerm" : {
    "kind" : "Action",
    "predicates" : [ {
      "kind" : "RootOperation",
      "attributes" : {
        "classLabel" : "WIDENING_OBSTACLE",
        "objLabel" : ""
      },
      "predicates" : [ {
        "kind" : "CreateObjectOperation",
        "attributes" : {
          "classLabel" : "Report",
          "objLabel" : ""
        },
        "predicates" : [ {
          "kind" : "SequenceOperation",
          "predicates" : [ {
            "kind" : "AssignmentOperation",
            "predicates" : [ {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "",
                "propName" : "geometry",
                "classRef" : "Report"
              }
            }, {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "",
                "propName" : "geometry",
                "classRef" : "WIDENING_OBSTACLE"
              }
            } ]
          }, {
            "kind" : "AssignmentOperation",
            "predicates" : [ {
              "kind" : "DynamicValue",
              "attributes" : {
                "objRef" : "",
                "propName" : "Note",
                "classRef" : "Report"
              }
            }, {
              "kind" : "SummedValue",
              "predicates" : [ {
                "kind" : "ClassValue",
                "attributes" : {
                  "objRef" : "",
                  "classRef" : "WIDENING_OBSTACLE"
                }
              }, {
                "kind" : "StaticValue",
                "attributes" : {
                  "datatype" : "string",
                  "value" : " object has an invalid Value_Text."
                }
              } ]
            } ]
          } ]
        } ]
      } ]
    } ]
  },
  "template" : false
}